Web/Europa.Web/Areas/Admin/Controllers/CategoryController.cs
using AutoMapper;
using Europa.Web.Areas.Admin.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Europa.Infrastructure;
using Europa.Query.Messages;
using Europa.Query.Messages.Models;
using Europa.Write.Messages;

namespace Europa.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoryController : Controller
    {
        private readonly ICommandDispatcher _commands;
        private readonly IQueryDispatcher _queries;

        public CategoryController(ICommandDispatcher commands, IQueryDispatcher queries)
        {
            _commands = commands;
            _queries = queries;
        }

        public async Task<IActionResult> Index(Guid id)
        {
            var categoryResult = await _queries.Request<GetCategoryQuery, GetCategoryQueryResult>(new GetCategoryQuery { Id = id });
            var podcastsResult = await _queries.Request<GetPodcastsQuery, GetPodcastsQueryResult>(new GetPodcastsQuery { CategoryId = id });
            var model = new CategoryPageModel
            {
                Category = Mapper.Map<Category, CategoryViewModel>(categoryResult.Category),
                Podcasts = Mapper.Map<IEnumerable<Podcast>, IEnumerable<PodcastViewModel>>(podcastsResult.Podcasts)
            };
            return View(model);
        }

        public async Task<IActionResult> Edit(Guid id)
        {
            var query = new GetCategoryQuery { Id = id };
            var result = await _queries.Request<GetCategoryQuery, GetCategoryQueryResult>(query);
            var model = Mapper.Map<Category, CategoryEditModel>(result.Category);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(CategoryEditModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            await _commands.Send(new CreateCategoryCommand { Id = model.Id, Name = model.Name });

            return RedirectToAction("Index", new { id = model.Id });
        }


        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CategoryCreateModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var id = Guid.NewGuid();
            await _commands.Send(new CreateCategoryCommand { Id = id, Name = model.Name });

            return RedirectToAction("ForCategoryCreation", "Wait", new { Id = id });
        }

        public async Task<IActionResult> Delete(Guid id)
        {
            var command = new DeleteCategoryCommand { Id = id };
            await _commands.Send(command);
            return RedirectToAction("Index", "Dashboard");
        }
    }
}

Web/Europa.Web/Controllers/ProductController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using Europa.Web.Models;
using AutoMapper;
using System.Threading.Tasks;
using Europa.Infrastructure;
using Europa.Query.Messages;
using Europa.Query.Messages.Models;

namespace Europa.Web.Controllers
{
    public class PodcastController : Controller
    {
        private readonly IQueryDispatcher _queries;
        
        public PodcastController(IQueryDispatcher queries)
        {
            _queries = queries;
        }

        public async Task<IActionResult> Index(Guid id)
        {
            var podcastResult = await _queries.Request<GetPodcastQuery, GetPodcastQueryResult>(new GetPodcastQuery { Id = id });
            var categoryResult = await _queries.Request<GetCategoryQuery, GetCategoryQueryResult>(new GetCategoryQuery { Id = podcastResult.Podcast.Id });
            var model = new PodcastPageModel
            {
                Category = Mapper.Map<Category, CategoryViewModel>(categoryResult.Category),
                Podcast = Mapper.Map<Podcast, PodcastViewModel>(podcastResult.Podcast)
            };
            return View(model);
        }
    }
}

Web/Europa.Web/Areas/Admin/Views/Category/Create.cshtml
@model CategoryCreateModel

<div class="panel panel-primary">
    <div class="panel-heading">
        <h4>Create Category</h4>
    </div>
    <div class="panel-body">
        <form asp-action="Create" method="POST">
            
            <div asp-validation-summary="All"></div>

            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <div>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group" style="margin-top:10px">
                <button asp- class="btn btn-primary">Submit</button>
            </div>
        </form>
    </div>
</div>

Web/Europa.Web/Areas/Admin/Views/Category/Edit.cshtml
@model CategoryEditModel

<div class="panel panel-primary">
    <div class="panel-heading">
        <h4>Edit Category</h4>
    </div>
    <div class="panel-body">
        <form asp-action="Edit" method="POST">

            <div asp-validation-summary="All"></div>

            <input asp-for="Id" type="hidden" />
            
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <div>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>
            
            <div class="form-group" style="margin-top:10px">
                <button asp- class="btn btn-primary">Submit</button>
            </div>

        </form>
    </div>
</div>

Web/Europa.Web/Areas/Admin/Views/Category/Index.cshtml
@model CategoryPageModel

<div class="panel panel-primary">
    <div class="panel-heading">
        <div class="btn-group pull-right">
            <a asp-action="Edit" asp-route-id="@Model.Category.Id" class="btn btn-default">Edit Category</a>
            <a asp-action="Create" asp-controller="Podcast" asp-route-id="@Model.Category.Id" class="btn btn-default">Create Podcast</a>
        </div>
        <h4>Category: @Model.Category.Name</h4>
    </div>
    <div class="panel-body">
        <table class="table table-bordered table-hover table-striped">
            <thead>
            <tr>
                <th>Product</th>
                <th>Edit</th>
                <th>Delete</th>
            </tr>
            </thead>
            @foreach (var podcast in Model.Podcasts)
            {
                <tr>
                    <td><a asp-controller="Product" asp-action="Index" asp-route-id="@podcast.Id">@podcast.Title</a></td>
                    <td><a asp-controller="Product" asp-action="Edit" asp-route-id="@podcast.Id">Edit</a></td>
                    <td><a asp-controller="Product" asp-action="Delete" asp-route-id="@podcast.Id" class="text-danger">Delete</a></td>
                </tr>
            }
        </table>
    </div>
</div>